dist: xenial

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"


cache: pip

install:
  - pip install .
  - pip install tox-travis
  - pip install coveralls

script:
  - tox

after_success:
  - coveralls
  - coverage report -m

notifications:
  irc: "chat.freenode.net#pycounter"

jobs:
  include:
  - python: 3.7
    env: TOXENV=flake8
  - python: 2.7
    env: TOXENV=flake8_py2
  - python: 3.7
    env: TOXENV=manifest
  - python: 3.6
    env: TOXENV=lint
  - python: 3.7
    env: TOXENV=docs

deploy:
  provider: pypi
  user: Wooble
  password:
    secure: hCCjmC5IU/Ch5Ux1WpOwnI5/veifCQ4uTs7z6HL7tQaaFkLArGlTSKuAGTs8P753PlxJwTiLvjYRkjHt0Tzav6GoZ3TkU4/QHnd6JZLhOth9uTj7ENgW3kWJ1zwZU9acLqDub1jqXglJVUWk6Ave1UMkNLFfhSnLW+v4x8m94Ww=
  on:
    condition: "! $TOXENV =~ ^flake8|lint|manifest|docs$"
    tags: true
    python: 3.6
  distributions: "sdist bdist_wheel"
