dist: xenial

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

cache: pip

install:
  - pip install .
  - pip install tox-travis
  - pip install coveralls

script:
  - tox

after_success:
  - coveralls
  - coverage report -m

notifications:
  irc: "irc.libera.chat#pycounter"

jobs:
  include:
  - python: 3.7
    env: TOXENV=flake8
  - python: 3.7
    env: TOXENV=manifest
  - python: 3.7
    env: TOXENV=lint
  - python: 3.7
    env: TOXENV=docs
  - python: "pypy3.6-7.0.0"
    env: TOXENV=pypy3_linux

deploy:
  provider: pypi
  user: Wooble
  password:
    secure: hCCjmC5IU/Ch5Ux1WpOwnI5/veifCQ4uTs7z6HL7tQaaFkLArGlTSKuAGTs8P753PlxJwTiLvjYRkjHt0Tzav6GoZ3TkU4/QHnd6JZLhOth9uTj7ENgW3kWJ1zwZU9acLqDub1jqXglJVUWk6Ave1UMkNLFfhSnLW+v4x8m94Ww=
  on:
    condition: "! $TOXENV =~ ^flake8|lint|manifest|docs$"
    tags: true
    python: 3.6
  distributions: "sdist bdist_wheel"
