sudo: false
dist: trusty

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

cache: pip

install:
  - pip install .
  - pip install tox-travis
  - pip install coverage
  - pip install coveralls


script:
  - tox

after_success:
  - coveralls
  - coverage report -m

notifications:
  irc: "chat.freenode.net#pycounter"

jobs:
  include:
  - python: 3.6
    env: TOXENV=flake8
  - python: 2.7
    env: TOXENV=flake8_py2
  - python: 3.6
    env: TOXENV=manifest
  - python: 3.6
    env: TOXENV=lint
  - python: "3.7"
    dist: "xenial"
    sudo: true
    script: tox

deploy:
  provider: pypi
  user: Wooble
  password:
    secure: hCCjmC5IU/Ch5Ux1WpOwnI5/veifCQ4uTs7z6HL7tQaaFkLArGlTSKuAGTs8P753PlxJwTiLvjYRkjHt0Tzav6GoZ3TkU4/QHnd6JZLhOth9uTj7ENgW3kWJ1zwZU9acLqDub1jqXglJVUWk6Ave1UMkNLFfhSnLW+v4x8m94Ww=
  on:
    condition: "! $TOXENV =~ ^flake8|lint|manifest$"
    tags: true
    python: 3.6
  distributions: "sdist bdist_wheel"
