version: 1.0.{build}
build: off

environment:
  matrix:
  - TOXENV: py27
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37

install:
  - python -m pip install --ignore-installed -U pip
  - pip install tox

test_script:
  - tox
